App\Domain\Basket\Basket:
  type: entity
  table: baskets
  repositoryClass: App\Infrastructure\DoctrineBasketRepository
  id:
    id:
      type: basket_id
      generator:
        strategy: CUSTOM
      customIdGenerator:
        class: App\Infrastructure\BasketIdGenerator

  embedded:
    name:
      class: App\Domain\Basket\BasketName
      columnPrefix: false
    maxCapacity:
      class: App\Domain\Basket\Weight
      columnPrefix: false

  fields:
    contents:
      type: basket_contents
      nullable: true